// Generated by scripts/import_excel.py — do not edit by hand.
export const COUNTRY_LIST: { name: string; slug: string; flag: string }[] = [
 {
  "name": "Albania",
  "slug": "albania",
  "flag": "🇦🇱"
 },
 {
  "name": "Australia",
  "slug": "australia",
  "flag": "🇦🇺"
 },
 {
  "name": "Austria",
  "slug": "austria",
  "flag": "🇦🇹"
 },
 {
  "name": "Belgium",
  "slug": "belgium",
  "flag": "🇧🇪"
 },
 {
  "name": "Bulgaria",
  "slug": "bulgaria",
  "flag": "🇧🇬"
 },
 {
  "name": "Canada",
  "slug": "canada",
  "flag": "🇨🇦"
 },
 {
  "name": "China",
  "slug": "china",
  "flag": "🇨🇳"
 },
 {
  "name": "Croatia",
  "slug": "croatia",
  "flag": "🇭🇷"
 },
 {
  "name": "Cyprus",
  "slug": "cyprus",
  "flag": "🇨🇾"
 },
 {
  "name": "Czech Republic",
  "slug": "czech-republic",
  "flag": "🇨🇿"
 },
 {
  "name": "Denmark",
  "slug": "denmark",
  "flag": "🇩🇰"
 },
 {
  "name": "Estonia",
  "slug": "estonia",
  "flag": "🇪🇪"
 },
 {
  "name": "Finland",
  "slug": "finland",
  "flag": "🇫🇮"
 },
 {
  "name": "France",
  "slug": "france",
  "flag": "🇫🇷"
 },
 {
  "name": "Georgia",
  "slug": "georgia",
  "flag": "🇬🇪"
 },
 {
  "name": "Germany",
  "slug": "germany",
  "flag": "🇩🇪"
 },
 {
  "name": "Greece",
  "slug": "greece",
  "flag": "🇬🇷"
 },
 {
  "name": "Hungary",
  "slug": "hungary",
  "flag": "🇭🇺"
 },
 {
  "name": "Iceland",
  "slug": "iceland",
  "flag": "🇮🇸"
 },
 {
  "name": "Ireland",
  "slug": "ireland",
  "flag": "🇮🇪"
 },
 {
  "name": "Italy",
  "slug": "italy",
  "flag": "🇮🇹"
 },
 {
  "name": "Japan",
  "slug": "japan",
  "flag": "🇯🇵"
 },
 {
  "name": "Kosovo",
  "slug": "kosovo",
  "flag": "🇽🇰"
 },
 {
  "name": "Latvia",
  "slug": "latvia",
  "flag": "🇱🇻"
 },
 {
  "name": "Liechtenstein",
  "slug": "liechtenstein",
  "flag": "🇱🇮"
 },
 {
  "name": "Lithuania",
  "slug": "lithuania",
  "flag": "🇱🇹"
 },
 {
  "name": "Luxembourg",
  "slug": "luxembourg",
  "flag": "🇱🇺"
 },
 {
  "name": "Malta",
  "slug": "malta",
  "flag": "🇲🇹"
 },
 {
  "name": "Montenegro",
  "slug": "montenegro",
  "flag": "🇲🇪"
 },
 {
  "name": "Netherlands",
  "slug": "netherlands",
  "flag": "🇳🇱"
 },
 {
  "name": "New Zealand",
  "slug": "new-zealand",
  "flag": "🇳🇿"
 },
 {
  "name": "Norway",
  "slug": "norway",
  "flag": "🇳🇴"
 },
 {
  "name": "Poland",
  "slug": "poland",
  "flag": "🇵🇱"
 },
 {
  "name": "Portugal",
  "slug": "portugal",
  "flag": "🇵🇹"
 },
 {
  "name": "Romania",
  "slug": "romania",
  "flag": "🇷🇴"
 },
 {
  "name": "Serbia",
  "slug": "serbia",
  "flag": "🇷🇸"
 },
 {
  "name": "Singapore",
  "slug": "singapore",
  "flag": "🇸🇬"
 },
 {
  "name": "Slovakia",
  "slug": "slovakia",
  "flag": "🇸🇰"
 },
 {
  "name": "Slovenia",
  "slug": "slovenia",
  "flag": "🇸🇮"
 },
 {
  "name": "Spain",
  "slug": "spain",
  "flag": "🇪🇸"
 },
 {
  "name": "Sweden",
  "slug": "sweden",
  "flag": "🇸🇪"
 },
 {
  "name": "Switzerland",
  "slug": "switzerland",
  "flag": "🇨🇭"
 },
 {
  "name": "UAE",
  "slug": "uae",
  "flag": "🇦🇪"
 },
 {
  "name": "USA",
  "slug": "usa",
  "flag": "🇺🇸"
 },
 {
  "name": "United Kingdom",
  "slug": "united-kingdom",
  "flag": "🇬🇧"
 }
];
export const DEPARTMENTS: string[] = [
 "Architecture",
 "Architecture and Urban Design",
 "Bio",
 "Biomedical",
 "Biomedical Engineering and Life Sciences",
 "Bioscience Engineering",
 "Biotechnology and Health",
 "Business",
 "Business & Management",
 "Business & Mgmt",
 "Business and Management",
 "Business or Economics",
 "Chemistry",
 "Computer Science",
 "Computer science",
 "Cultural Heritage and Tourism",
 "Data Science and Artificial Intelligence",
 "Design",
 "Economics",
 "Economics and Business",
 "Economics and Finance",
 "Engineering",
 "Engineering & IT",
 "Engineering and Applied Sciences",
 "Engineering and Technology",
 "Faculty of Engineering Science",
 "Finance & Economics",
 "Finance and Accounting",
 "Geosciences",
 "Health Sciences",
 "History",
 "History/Design",
 "IR",
 "IT",
 "International Relations and Politics",
 "Law",
 "Law and Justice",
 "Linguistics",
 "Literature",
 "Management",
 "Mathematics and Applied Sciences",
 "Medicine",
 "Molecular",
 "Molecular Sciences",
 "Movement and Rehabilitation Sciences",
 "Neuroscience",
 "Neuroscience and Psychology",
 "Philosophy",
 "Physics and Astrophysics",
 "Political Science",
 "Political and Social Sciences",
 "Psychology",
 "Science",
 "Social Sciences",
 "Statistical Science",
 "Statistics",
 "Tourism",
 "hospitality"
];
export const LEVELS = ["Bachelor", "Master", "PhD"];
